version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_AUTH_BASE_URL=${NEXT_PUBLIC_AUTH_BASE_URL}
        - NEXT_PUBLIC_CHAT_BASE_URL=${NEXT_PUBLIC_CHAT_BASE_URL}
        - NEXT_PUBLIC_KONSULTASI_BASE_URL=${NEXT_PUBLIC_KONSULTASI_BASE_URL}
        - NEXT_PUBLIC_DOCTOR_LIST_BASE_URL=${NEXT_PUBLIC_DOCTOR_LIST_BASE_URL}
        - NEXT_PUBLIC_RATING_BASE_URL=${NEXT_PUBLIC_RATING_BASE_URL}
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge