name: Deploy Frontend

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set environment variables
        id: env
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "ENV_MODE=production" >> $GITHUB_ENV
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_API_AUTH_URL=${{ secrets.NEXT_PUBLIC_AUTH_BASE_URL }}" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_API_CHAT_URL=${{ secrets.NEXT_PUBLIC_CHAT_BASE_URL }}" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_API_KONSULTASI_URL=${{ secrets.NEXT_PUBLIC_KONSULTASI_BASE_URL }}" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_API_PROFILE_URL=${{ secrets.NEXT_PUBLIC_PROFILE_BASE_URL }}" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_API_RATING_URL=${{ secrets.NEXT_PUBLIC_RATING_BASE_URL }}" >> $GITHUB_ENV
          else
            echo "ENV_MODE=development" >> $GITHUB_ENV
            echo "DOCKER_TAG=dev" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_API_AUTH_URL=${{ secrets.NEXT_PUBLIC_AUTH_BASE_URL }}" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_API_CHAT_URL=${{ secrets.NEXT_PUBLIC_CHAT_BASE_URL }}" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_API_KONSULTASI_URL=${{ secrets.NEXT_PUBLIC_KONSULTASI_BASE_URL }}" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_API_PROFILE_URL=${{ secrets.NEXT_PUBLIC_PROFILE_BASE_URL }}" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_API_RATING_URL=${{ secrets.NEXT_PUBLIC_RATING_BASE_URL }}" >> $GITHUB_ENV
          fi
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:${{ env.DOCKER_TAG }}
          build-args: |
            NODE_ENV=${{ env.ENV_MODE }}
            NEXT_PUBLIC_AUTH_BASE_URL=${{ env.API_AUTH_URL }}
            NEXT_PUBLIC_CHAT_BASE_URL=${{ env.API_CHAT_URL }}
            NEXT_PUBLIC_KONSULTASI_BASE_URL=${{ env.API_KONSULTASI_URL }}
            NEXT_PUBLIC_PROFILE_BASE_URL=${{ env.API_PROFILE_URL }}
            NEXT_PUBLIC_RATING_BASE_URL=${{ env.API_RATING_URL }}
            
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:${{ env.DOCKER_TAG }}
            docker stop frontend-${{ env.ENV_MODE }} || true
            docker rm frontend-${{ env.ENV_MODE }} || true
            docker run -d \
              --name frontend-${{ env.ENV_MODE }} \
              -p ${{ env.ENV_MODE == 'production' && '3000:3000' || '3001:3000' }} \
              --restart always \
              ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:${{ env.DOCKER_TAG }}