name: Deploy Frontend to EC2

on:
  push:
    branches: [ main, dev ] 
  pull_request:
    branches: [ main, dev ]  

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            
            # Check if the repo exists, if so pull latest changes, otherwise clone
            if [ -d "frontend" ]; then
              cd frontend
              git fetch
              git checkout ${{ github.ref_name }}
              git pull
            else
              git clone -b ${{ github.ref_name }} https://github.com/${{ github.repository }}.git frontend
              cd frontend
            fi
            
            cat > .env << EOL
            NEXT_PUBLIC_AUTH_BASE_URL=${{ secrets.NEXT_PUBLIC_AUTH_BASE_URL }}
            NEXT_PUBLIC_CHAT_BASE_URL=${{ secrets.NEXT_PUBLIC_CHAT_BASE_URL }}
            NEXT_PUBLIC_KONSULTASI_BASE_URL=${{ secrets.NEXT_PUBLIC_KONSULTASI_BASE_URL }}
            NEXT_PUBLIC_PROFILE_BASE_URL=${{ secrets.NEXT_PUBLIC_PROFILE_BASE_URL }}
            NEXT_PUBLIC_RATING_BASE_URL=${{ secrets.NEXT_PUBLIC_RATING_BASE_URL }}
            EOL
            
            if ! [ -x "$(command -v docker)" ]; then
              echo 'Installing Docker...'
              sudo apt-get update
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
              
              sudo systemctl start docker
              sudo systemctl enable docker
              
              sudo usermod -aG docker $USER
            fi
            
            if ! [ -x "$(command -v docker-compose)" ] && ! [ -x "$(command -v docker compose)" ]; then
              echo 'Installing Docker Compose...'
              DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
              mkdir -p $DOCKER_CONFIG/cli-plugins
              COMPOSE_VERSION=v2.24.6
              sudo curl -SL "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              sudo ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
            fi
            
            echo "Using Docker Compose to deploy the application"
            
            sudo docker-compose down 
            
            sudo docker-compose build --no-cache
            sudo docker-compose up -d
            
            sudo docker-compose ps
            
            sudo docker system prune -f || true